
name: Update_COVID19_Argentina
on:
  push:
    branches: [ test_workflow ]
    paths:
      - 'data/casos.xlsx'
      - 'argentina_covid19_viz.py'

jobs:
  chartUpdate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.6'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Update Covid Charts 
      run: python argentina_covid19_viz.py

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

    - name: Commit changes
      uses: EndBug/add-and-commit@master
      with:
        author_name: felixlapalma
        author_email: felixlapalma@gmail.com
        message: "Update  ${{steps.date.outputs.date}}"
        add: "_includes/*.html"
      env:
       GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
